### PR TITLE
Add a newline to the end of all files that should have one

### PR DESCRIPTION
**Pull request by serebit**
https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

I'd also suggest enabling this setting in IntelliJ so that any new files will have newlines appended:

image

### CODE REVIEW

**Comment by serebit** [comment]
I'll be attempting a Linux X64 target after this and possibly after another kts-related PR.

**Comment by erikc5000** [comment]
Is there a particular tool that's problematic?

While I'm aware of the justification for ending newlines, I thought it was more of a historical issue at this point. Not opposed to changing the style, but would prefer not to muck with it unless it's really necessary.

**Comment by serebit** [comment]
Admittedly, I'm *mostly* doing this for personal reasons, but from a technical perspective it addresses two things.
- Consistency: There are files in the source code of island-time that *do* end with newlines, but the majority don't. This PR addresses this and introduces a consistent style across all source files.
- CLI tool compatibility: As stated in the Stack Exchange post, having a newline at EOF is expected behavior by grep and sed.

**Comment by erikc5000** [comment]
Fair enough - I'm alright with switching over to ending newlines. Just rebase to master first since I merged in a few PRs and moved it to Kotlin 1.4. The plan is for the next release, 0.3.0, to roughly coincide with the release of Kotlin 1.4.0 final.

When you talk about KTS changes, do you mean the precompiled script plugins? Those have proven to be quite problematic and basically a sea of red in IntelliJ when using Kotlin 1.4, so I've been looking at maybe migrating them to regular ".kt" files in the hope that it will work better.

**Comment by serebit** [comment]
Rebase done. And the precompiled script plugins are something I can look into.

**Comment by erikc5000** [comment]
I won't be able to look into much over the next week or so, so feel free. It'd be good to make the IDE happy again -- if that's even possible. Same goes for the classpath conflict warnings.

**Pull request merged**
